// <auto-generated />
namespace AuthorizeyAllowAnonymous.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Agrego_Columna_NacimientoS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Agrego_Columna_NacimientoS));
        
        string IMigrationMetadata.Id
        {
            get { return "201905141558351_Agrego_Columna_NacimientoS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
