// <auto-generated />
namespace Paginacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Primera_Migracion : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Primera_Migracion));
        
        string IMigrationMetadata.Id
        {
            get { return "201905022139556_Primera_Migracion"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
